spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/somenbag/microservice-config.git"
          default-label: eazybank
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

#default-label: This specifies the default branch or label to use when accessing the Git repository.
#timeout: This specifies the timeout (in seconds) for accessing the Git repository.
#clone-on-start: true (the cloning of the GitHub repository into local system happen during the start-up itself)
#force-pull: true (would instruct the Spring Cloud Config Server to perform a force pull from the Git repository every time a client requests configuration data, ensuring that clients always receive the latest configuration changes.)